# Production-specific configuration properties
spring:
  config:
    activate:
      on-profile: production
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/raya?createDatabaseIfNotExist=true
    username: camelsoft
    password: camelsoft
    #url: jdbc:postgresql://node21801-suppliers.paas5.v2.sa:11003/raya?createDatabaseIfNotExist=true&sslmode=require
    #username: webadmin
    #password: XILntg88398
logging:
  level:
    org:
      hibernate: ERROR
  file:
    name: /var/lib/jenkins/workspace/rayaserver/src/main/resources/${spring.application.name}.log
