# Production-specific configuration properties
spring:
  config:
    activate:
      on-profile: production
  datasource:
    url: jdbc:postgresql://172.30.130.183:5432/raya?createDatabaseIfNotExist=true&sslmode=require
    username: camelsoft
    password: camelsoft
    driver-class-name: org.postgresql.Driver
logging:
  level:
    org:
      hibernate: ERROR
  file:
    name: /var/lib/jenkins/workspace/rayaserver/src/main/resources/${spring.application.name}.log
