# Test-specific configuration properties
spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/pfe?createDatabaseIfNotExist=true
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
logging:
  level:
    org:
      hibernate: ERROR
  #  root: DEBUG


