# Test-specific configuration properties
spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/raya?createDatabaseIfNotExist=true
    username: camelsoft
    password: camelsoft
    driver-class-name: org.postgresql.Driver
logging:
  level:
    org:
      hibernate: ERROR
  #  root: DEBUG
  file:
    name: /var/lib/jenkins/workspace/rayaserver/src/main/resources/${spring.application.name}.log


