# Test-specific configuration properties
spring:
  minio:
    url: https://os.ruh.cloudsigma.com
    bucket: rayafinancing.v2
    access-key: 1cUDYC4RTXUW00zgrtqV
    secret-key: SNNY7WTETW3YCJFOJVu4aNhW7HxzXARV0WELQlQW
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/raya?createDatabaseIfNotExist=true
    username: camelsoft
    password: camelsoft
    driver-class-name: org.postgresql.Driver
logging:
  level:
    org:
      hibernate: ERROR
  #  root: DEBUG
  file:
    name: /var/lib/jenkins/workspace/rayaserver/src/main/resources/${spring.application.name}.log


