# Production-specific configuration properties
spring:
  config:
    activate:
      on-profile: production
  datasource:
    url: jdbc:postgresql://node21801-suppliers.paas5.v2.sa:11003/raya?createDatabaseIfNotExist=true
    username: webadmin
    password: XILntg88398
logging:
  level:
    org:
      hibernate: ERROR
  file:
    name: ${spring.application.name}.log
