package com.smarty.pfeserver.Enum.Project;

public enum SoftSkillsEnum {
    COMMUNICATION,
    TEAMWORK,
    PROBLEM_SOLVING,
    TIME_MANAGEMENT,
    ADAPTABILITY,
    WORK_ETHIC,
    CREATIVITY,
    LEADERSHIP,
    ATTENTION_TO_DETAIL,
    CRITICAL_THINKING,
    EMOTIONAL_INTELLIGENCE,
    DECISION_MAKING,
    CONFLICT_RESOLUTION,
    COLLABORATION,
    SELF_MOTIVATION,
    PATIENCE,
    STRESS_MANAGEMENT,
    ACTIVE_LISTENING,
    INTERPERSONAL_SKILLS,
    NEGOTIATION
}
