package com.camelsoft.rayaserver.Enum.User;

public enum UserActionsEnum {
    SUPPLIER_MANAGEMENT,
    AGENT_MANAGEMENT,
    PRIVILEGE_MANAGEMENT,
    LOAN_MANAGEMENT,
    INVOICE_MANAGEMENT,
    CUSTOMER_MANAGEMENT,
    PURCHASE_ORDER_MANAGEMENT,
    CHATTING,
    EVENT_MANAGEMENT,
    REQUEST_MANAGEMENT,
    SETTINGS_MANAGEMENT,
    STATS_READ,
    NOTIFICATION_READ,
    PROFILE_MANAGEMENT,
    DEPARTMENT_MANAGEMENT,
}
